# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def is_even(num)
    if num % 2 == 0
        return num
    else
        return 0
    end
end

limit = 4_000_000
a = 1
b = a + a
sum = 2

while b <= limit
    a += b
    b += a
    if b <= limit
        sum += is_even(a)
        sum += is_even(b)
    end
end

puts sum
