<?php
// Each new term in the Fibonacci sequence is generated by adding
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

function isEven($num) {
    if($num % 2 === 0) return true;
    else return false;
}

function fib($limit) {
    $a = 1; $b = $a + $a; $sum = 2;
    while($a + $b < $limit) {
        $a += $b;
        $b += $a;
        if(isEven($a)) $sum += $a;
        if(isEven($b)) $sum += $b;
    }
    return $sum;
}

echo fib(4000000);

?>
